version: '3.9'
services:
  # django:
  #   build:
  #     context: ./django
  #   ports:
  #     - "8000:8000"

  flask:
    build:
      context: ./flask
    ports:
      - "5000:5000"

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
